// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RMD.Data.Context;

#nullable disable

namespace RMD.Data.Migrations
{
    [DbContext(typeof(RMDContext))]
    [Migration("20240902235052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RMD.Data.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoundcloudUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            FacebookUrl = "https://www.facebook.com/RejackHS",
                            Name = "Rejack",
                            Nationality = "🇳🇴 Norge",
                            ProfilePicUrl = "https://www.test.com/",
                            SoundcloudUrl = "https://www.soundcloud.com/RejackHS"
                        },
                        new
                        {
                            ArtistId = 2,
                            FacebookUrl = "https://www.facebook.com/RejackHS",
                            Name = "Rejack 2",
                            Nationality = "🇳🇴 Norge",
                            ProfilePicUrl = "https://www.test.com/",
                            SoundcloudUrl = "https://www.soundcloud.com/RejackHS"
                        });
                });

            modelBuilder.Entity("RMD.Data.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongId"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExtendedMix")
                        .HasColumnType("bit");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Played")
                        .HasColumnType("bit");

                    b.Property<int?>("PlayedInEp")
                        .HasColumnType("int");

                    b.Property<bool>("RadioMix")
                        .HasColumnType("bit");

                    b.Property<string>("RemixArtist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Stored")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Wanted")
                        .HasColumnType("bit");

                    b.HasKey("SongId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            Artist = "Artist",
                            ExtendedMix = true,
                            Genre = "Hands Up",
                            Length = "02:23",
                            Played = true,
                            PlayedInEp = 18,
                            RadioMix = false,
                            RemixArtist = "Test",
                            Stored = true,
                            Title = "Hands Up Track (Test Remix)",
                            Wanted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
